#!/usr/bin/env bash
cd $(cd $(dirname $0); pwd)

memory_free=`awk '/^Mem/ {print $4}' <(free -m)`

if [ "$memory_free" -le 60 ]; then
	echo -e "\x1B[31m¦\n¦ CAUTION:\x1B[01;91m Your RAM size is less than 60MB.\n¦ NOW you can not install the SOURCE TH3BOSS. \n¦"
	echo -e "\x1B[01;90m¦ YOUR RAM FREE SIZE IS : \x1B[01;94m "$memory_free"MB\x1B[0m"
	exit 1
fi
echo -e "\x1B[01;90m\n¦ installing source ... \n\x1B[0m"
sudo apt-get update -y
sudo apt-get upgrade -y
echo -e "\x1B[01;90m\n¦ models installing ... \n\x1B[0m"
sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev lua-socket lua-sec lua-expat libevent-dev make unzip git redis-server autoconf g++ libjansson-dev libpython-dev expat libexpat1-dev  -y
echo -e "\x1B[01;90m\n¦ lua-lgi installing ...\n \x1B[0m"
sudo apt-get install lua-lgi -y
echo -e "\x1B[01;90m\n¦ software-properties-common installing ... \n\x1B[0m"
sudo apt-get install software-properties-common -y
echo -e "\x1B[01;90m\n¦ ubuntu-toolchain installing ...\n \x1B[0m"
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
echo -e "\x1B[01;90m\n¦ libstdc++6 installing ... \n\x1B[0m"
sudo apt-get install libstdc++6 -y
echo -e "\x1B[01;90m\n¦ update ... \n\x1B[0m"
sudo apt-get update -y
echo -e "\x1B[01;90m\n¦ upgrade ...\n \x1B[0m"
sudo apt-get upgrade -y
echo -e "\x1B[01;90m\n¦ dist-upgrade ... \n\x1B[0m"
sudo apt-get dist-upgrade -y
# BY _ [ sajad >> @sajadhassan ]
echo -e "\x1B[01;90m\n¦ Download luarocks v2.4.3 ... \n\x1B[0m"
 wget https://luarocks.org/releases/luarocks-2.4.3.tar.gz
 tar zxpf luarocks-2.4.3.tar.gz
 cd luarocks-2.4.3
 echo -e "\x1B[01;90m\n¦ ./configure AND make bootstrap ...\n \x1B[0m"
 ./configure; sudo make bootstrap
 sudo luarocks install luasocket
 echo -e "\x1B[01;90m\n¦ luasocket installing ...\n \x1B[0m"
 sudo luarocks install luasec
 echo -e "\x1B[01;90m\n¦ redis-lua installing ... \n\x1B[0m"
 sudo luarocks install redis-lua
  echo -e "\x1B[01;90m\n¦ lua-cjson installing ... \n\x1B[0m"
 sudo  luarocks install lua-cjson2
 echo -e "\x1B[01;90m\n¦ Lua-cURL installing ...\n \x1B[0m"
 sudo luarocks install Lua-cURL
 echo -e "\x1B[01;90m\n¦ redis-server start ...\n \x1B[0m"
 sudo service redis-server start
 echo -e "\x1B[01;90m\n¦ ppa:ubuntu-toolchain-r/test ... \n\x1B[0m"
 sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 echo -e "\x1B[01;90m\n¦  g++-4.7 -y c++-4.7 installing ... \n\x1B[0m"
 sudo apt-get install g++-4.7 -y c++-4.7
 echo -e "\x1B[01;90m\n¦ luasocket installing ...\n \x1B[0m"
 sudo apt-get install libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y
 echo -e "\x1B[01;90m\n¦ screen installing ... \n\x1B[0m"
 sudo apt-get install screen -y
 echo -e "\x1B[01;90m\n¦ libstdc++6 installing ... \n\x1B[0m"
 sudo apt-get install libstdc++6 -y
 echo -e "\x1B[01;90m\n¦ lua-lgi installing ... \n\x1B[0m"
 sudo apt-get install lua-lgi -y
 echo -e "\x1B[01;90m\n¦ libnotify installing ... \n\x1B[0m"
 sudo apt-get install libnotify-dev -y
 cd ..
 echo -e "\x1B[01;90m\n¦ Remove luarocks ... \n\x1B[0m"
 rm -rf ./luarocks-2.4.3
 rm  ./luarocks-2.4.3.tar.gz
 echo -e "\x1B[01;90m\n¦ Download TG ...\n \x1B[0m"
 wget https://valtman.name/files/telegram-cli-1222
 echo -e "\x1B[01;90m¦ Rename telegram-cli-1222 to TG  ... \x1B[0m"
 mv telegram-cli-1222 TG
 echo -e "\x1B[01;90m¦ chmod for TG  ... \x1B[0m"
 chmod +x TG
 echo -e "\x1B[01;90m¦ Open file BOT.lua and insert information  ... \x1B[0m"
 rm  ./inc/info.lua
 lua ./inc/BOT.lua
